### PR TITLE
Fixes #228 Encoding problem with observed data

### LINKED ISSUE #228: Encoding problem with observed data
when executing RE for the input attached, the error below appears
[reporting engine input.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3435054/reporting.engine.input.zip)
```

ERROR: Error in PKRatio plot 1 "Observed versus Predicted Clearance Ratio". 
 In PK Ratio Plot 1, Group 1, Ratio 1, Dimension unknown for Unit "�mol*h/l" in Observed Data Record ID "5301" 
```

the problem are some µ characters in the units saved in PKParameters.csv

### PR DESCRIPTION
**Pull request by Yuri05**

### CODE REVIEW

File: src/code/qualification/findDimensionfromUnit.m [hunk 1]
```diff
@@ -28,4 +31,22 @@
...
+    %If original character was not '�': exception will happen in any case (with or without replacement)
+    adjustedUnit(double(adjustedUnit)==65533)='�';
+
+    %if the unit was e.g. read from file which was saved using wrong encoding char(194) is added before/after some characters. just remove it
+    adjustedUnit = strrep(adjustedUnit,char(194),'');
+
+catch
+    %if something went wrong - return original unit
+    adjustedUnit = unit;
+end
```
Comment (Yuri05) [inline src/code/qualification/findDimensionfromUnit.m:52]: just some hacks. 
solves some problems with wrong encoding when reading/writing observed data files.

File: src/code/qualification/initializeQualificationWorkflow.m [hunk 2]
```diff
@@ -86,7 +86,7 @@
         % ObservedDataSets format to be determined
         % Temporary format: structure where the observed data is a table y
         if isfield(ConfigurationPlan.ObservedDataSets{i}, 'Type')
-            ObsTable = readtable(fullfile(REInput_path, ConfigurationPlan.ObservedDataSets{i}.Path), 'Encoding', 'UTF-8');
+            ObsTable = readtable(fullfile(REInput_path, ConfigurationPlan.ObservedDataSets{i}.Path), 'Encoding', 'system');
```
Comment (Yuri05) [inline src/code/qualification/initializeQualificationWorkflow.m:89]: From [readtable-documentation](https://de.mathworks.com/help/matlab/ref/readtable.html): `'Encoding', 'system' uses the system default encoding.`

This change solved the particular problem with observed data described in the referenced issue
(on my comp with german language settings and on another computer with english lang. settings).
This would theoretically make the hack above not necessary anymore.

however not sure if we will not get problems in other cases. If so, this change might be reverted

**Review by pchelle — APPROVED** [review]
Just wondering, 
Should readtable(... 'Encoding', 'system') be also implemented within loadObservationcsv and loadSimResultcsv as well ?

**Comment by Yuri05** [comment]
> Should readtable(... 'Encoding', 'system') be also implemented within loadObservationcsv and loadSimResultcsv as well ?

As long as we don't have any problems with observations/simresults exported by PK-Sim I would say: NO.
(I'm even not convinced that using encoding `system `is the proper way to handle this).
The problem with **user-generated** observed data: you never know with which (encoding) settings they were created.
PK-Sim generated files are always created the same way. And we didn't have problems with them so far with the current setting
