### PR TITLE
156 quali ontogeny

### LINKED ISSUE #174: Figure of example plot is incomplete
When running the Aciclovir example in the Reporting Engine, Figure 2 (Vergin 200 mg PO) is lacking the 2nd set of experimental data. As a consequence, the legend is also wrong. See attached picture.

002_plotTimeProfile
 
Compare this with the corresponding PK-Sim figure:
PK-Sim_Figure2

### LINKED ISSUE #177: Rerunning RE will append figures instead of overriding previous ones
When rerunning an example, the old figures are not overridden but instead new figure files are appended, starting with incrementing the last figure number of the previous run. So, if figures 001 to 003 were previously produced, the new figures are numbered from 004 to 006. 

Use the attached zip files from issues #174 and #175 to reproduce.

@Yuri05 and myself believe that this is **not** a feature.

### PR DESCRIPTION
**Pull request by pchelle**
Fixes #174 
Fixes #177

### CODE REVIEW

File: src/code/qualification/plotQualificationGOFMerged.m [hunk 1]
```diff
@@ -50,9 +50,24 @@
...
+        end
+        
         % Initialize simulation, and get Molecular Weight in g/mol for correct use of getUnitFactor
         initSimulation(xmlfile,'none');
-        MW = getMolecularWeightForPath(Simulations.Output);
+        % Get Molecular Weight for Conversion
+        try
+            MW = getMolecularWeightForPath(Simulations.Output);
+        catch
+            ME = MException('plotQualificationGOFMerged:notFoundInPath', ...
```
Comment (Yuri05) [inline src/code/qualification/plotQualificationGOFMerged.m]: set MW to NaN instead of throwing an exception

File: src/code/qualification/plotQualificationPKRatio.m [hunk 2]
```diff
@@ -51,23 +71,33 @@
...
         if ~isempty(findPathOutput)
-            Pred=SimResult.y{j};
-            PredUnit=SimResult.outputUnit{j};
-            SimTime=SimResult.time;
             SimTimeUnit=SimResult.timeUnit;
+            PredUnit=SimResult.outputUnit{j};
+            TimeUnitFactor=getUnitFactor(SimTimeUnit, 'h', 'Time');
+            PredUnitFactor=getUnitFactor(PredUnit, 'mg/l', 'Concentration', 'MW', MW);
+            
+            % Get Time in h and Concentraiton in g/l
```
Comment (Yuri05) [inline src/code/qualification/plotQualificationPKRatio.m]: First question: why do we convert to 'mg/l' and to 'h' here?
Second question: comment states 'g/l' (either the comment or the conversion is wrong)

File: src/code/qualification/plotQualificationPKRatio.m [hunk 3]
```diff
@@ -77,72 +107,62 @@
...
+        if strcmp(Result.obsPKDimension(i, k), 'AUC (mass)')
+            AUCpred = getfield(allPKpred, 'AUC_last');
+            AUCpredUnitFactor = getUnitFactor('mg*h/l', Result.obsPKUnit{i, k}, 'AUC (mass)', 'MW', MW);
+            Result.predPK(i, k) = AUCpred.*AUCpredUnitFactor;
+            
+        elseif strcmp(Result.obsPKDimension(i, k), 'Concentration')
+            
+            CMAXpred = getfield(allPKpred, 'cMax');
+            CMAXpredUnitFactor = getUnitFactor('mg/l', Result.obsPKUnit{i, k}, 'Concentration', 'MW', MW);
+            Result.predPK(i, k) = CMAXpred.*CMAXpredUnitFactor;
```
Comment (Yuri05) [inline src/code/qualification/plotQualificationPKRatio.m:130]: I don't understand this change. Please explain.

File: src/code/qualification/plotQualificationTimeProfile.m [hunk 4]
```diff
@@ -34,28 +34,31 @@ function plotQualificationTimeProfile(WSettings,figureHandle,TimeProfile,Observe
...
 hold on;
 
 % Plot the Curves indicated by the array of structures Curves
 for i=1:length(Curves)
     
+    % Get Molecular Weight for Conversion
+    try
+        MW = getMolecularWeightForPath(Curves(i).Y);
+    catch
+        ME = MException('plotQualificationTimeProfile:notFoundInPath', ...
```
Comment (Yuri05) [inline src/code/qualification/plotQualificationTimeProfile.m]: set MW to NaN instead of throwing an exception

**Review by Yuri05 — CHANGES_REQUESTED** [review]
If MW cannot be estimated from the curve path: set MW to NaN instead of throwing exception

File: src/code/qualification/plotQualificationPKRatio.m (hunk 2 above)
Comment (pchelle) [reply src/code/qualification/plotQualificationPKRatio.m]: 1) I wanted to have a known unique unit for flow, AUC and Cmax. I don't think I can know the unit after using getPKParametersForConcentration, so I converted everything before using it.
I think based on PKSim standard unit, concentration may be always in umol/ml, time in min and dose in umol. If it is the case, I can assume the standard unit to convert into the observed unit.
2) I started in g/l, wasn't in the unit list, so went for mg/l but forgot to update. I'm going to commit that change.

File: src/code/qualification/plotQualificationPKRatio.m (hunk 3 above)
Comment (pchelle) [reply src/code/qualification/plotQualificationPKRatio.m:130]: I assumed that Cmax can be a parameter requested in the PK ratio since it can for DDI Ratio.
If Cmax is requested, I convert it into the Observed Unit. And because I wanted the unit as mg, l and h for AUC and CL, the current unit for Cmax would be in mg/l

File: src/code/qualification/plotQualificationPKRatio.m (hunk 2 above)
Comment (Yuri05) [reply src/code/qualification/plotQualificationPKRatio.m]: Internal PK-Sim units are:
* `"µmol/L"` for **Concentration**
* `"min"` for **Time**

And times/concentration in simulation results CSVs are always in internal units (@msevestre correct me if I'm wrong)

Thus if times/concentrations in the internal units are passed to getPKParametersForConcentration, units for calculated PK-Parameters would be (@KatrinCoboeken correct me if I'm wrong)
* `"µmol/l"` for **CMax** (same as concentration)
* `"µmol*min/l"` for **AUC**
* `"l/min"` for **CL**

Comment (pchelle) [reply src/code/qualification/plotQualificationPKRatio.m]: Ok. I'll use directly these units then if that's okay.

Comment (Yuri05) [reply src/code/qualification/plotQualificationPKRatio.m]: By the end it's only important to use the **same units** when calculating `PKParameter.Predicted/PKParameter.Observed`.
Thus either predicted PKParameter must be converted into the unit of observed PK Parameter or vice versa

Comment (Yuri05) [reply src/code/qualification/plotQualificationPKRatio.m]: > 
> 
> Ok. I'll use directly these units then if that's okay.

should be ok

**Review by Yuri05 — APPROVED** [review]
