### PR TITLE
209 population plots

### LINKED ISSUE #106: Read in start time and end time for AUCR and CmaxR calculation from external data source
When reading in observed AUCR ("AUCR Avg") and CmaxR ("CmaxR Avg") for DDIRatioPlots, also read in start and end time, for which AUCR and CmaxR will be calculated in simulations.
Column Names will be:
"t_placebo_0", "t_placebo_end", "t_treatment_0", "t_treatment_end", "t Unit"

### LINKED ISSUE #209: Either mean line (linear scale) or range (log scale) are not visible in population plots
For all population simulations, when means and percentiles are created:

- In log-y scale the ranges (in grey) are never visible
- In linear-y scale the mean lines are never visible

Hope for asap correction.

### LINKED ISSUE #219: Error in DDI Ratio plot
Adjust the path and execute **Error_DDI_CYP3A4_Workflow.m**
This gives an error message below.

[Error_DDI-CYP3A4.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3359569/Error_DDI-CYP3A4.zip)

```
ERROR: Error in DDIRatio plot 1 "CYP3A4 DDI". 
 Formatted MESSAGE input may only include scalar numeric values and character vectors 

Warning: Error in DDIRatio plot 1 CYP3A4 DDI.
 Formatted MESSAGE input may only include scalar numeric values and character vectors
 
> In runQualificationWorkflow (line 371)
  In Error_DDI_CYP3A4_Workflow (line 14) 
```

### PR DESCRIPTION
**Pull request by pchelle**
Fixes #209 
Fixes #219

### CODE REVIEW

File: src/code/qualification/plotQualificationDDIRatio.m [hunk 1]
```diff
@@ -151,6 +160,15 @@
                 % Only get output in a time range defined by user
                 Xfactor=getUnitFactor(DDITimeUnit,DDIRatios(j).SimulationDDI.TimeUnit,'time');
                 
+                % If Start Time and End Time are empty, use min and max values of simulation
+                DDIRatios(j).SimulationDDI.StartTime(isempty(DDIRatios(j).SimulationDDI.StartTime)) = min(DDITime.*Xfactor);
+                DDIRatios(j).SimulationDDI.EndTime(isempty(DDIRatios(j).SimulationDDI.EndTime)) = max(DDITime.*Xfactor);
+                
+                % Check if end time was read as a string for Inf value
+                if strcmpi(DDIRatios(j).SimulationControl.EndTime, 'Inf')
```
Comment (Yuri05) [inline src/code/qualification/plotQualificationDDIRatio.m]: must be SimulationDDI
Copy/Paste is dangerous...

**Comment by Yuri05** [comment]
@pchelle Please remove "Fixes #106" from the PR description.
106 is not fixed with this PR. This issue is about reading Min/Max ranges from the **Observed data set** and not from the qualification plan.
Also 106 is not that urgent (that's why it's set to Milestone 3)

File: src/code/qualification/plotQualificationDDIRatio.m [hunk 2]
```diff
@@ -181,7 +199,11 @@
         for k=1:length(PKParameter)
             % Get the PK parameters requested in PKParameter
             if strcmpi(PKParameter{k}, 'AUC')
-                PKpredField{k}= 'AUC_last';
+                if isinf(DDIRatios(j).SimulationControl.EndTime) && isinf(DDIRatios(j).SimulationDDI.EndTime)
+                    PKpredField{k}= 'AUC_inf';
+                else
+                    PKpredField{k}= 'AUC_last';
+                end
```
Comment (Yuri05) [inline src/code/qualification/plotQualificationDDIRatio.m:206]: @sfrechen Is this how it is expected to work?

File: src/code/qualification/plotQualificationTimeProfile.m [hunk 3]
```diff
@@ -265,50 +265,57 @@ function plotQualificationTimeProfile(WSettings,figureHandle,TimeProfile,Observe
...
     end
     if contains(Curves.Statistics(i).Id, 'Range')
         perc = sscanf(Curves.Statistics(i).Id, 'Range%d')/100;
         ran = quantile(Y, [(1-perc)/2 (1+perc)/2]);
+        if strcmpi(Scaling, 'Log')
+            % Remove 0s from plot in log
+            zeros2remove = min(ran==0);
+            time(zeros2remove) = [];
+            ran(:,zeros2remove) = [];
+        end
```
Comment (Yuri05) [inline src/code/qualification/plotQualificationTimeProfile.m:315]: @pchelle This is the fix for _not-displayed range in log scale_. Can you tell me where the other case (_Mean curve hidden by the range in lin scale_) is fixed?

Comment (pchelle) [reply src/code/qualification/plotQualificationTimeProfile.m:315]: Yes, the other issue was that the range is not transparent and hide the mean curve.
I handled the issue by setting transparency line 319: set(p_handle(i), 'FaceAlpha', 0.5); 
The other solution would be to re-order the plots and always having the range before the other population time plots.

File: src/code/qualification/plotQualificationDDIRatio.m (hunk 2 above)
Comment (Yuri05) [reply src/code/qualification/plotQualificationDDIRatio.m:206]: @sfrechen Please comment on this

File: src/code/qualification/plotQualificationComparisonTimeProfile.m [hunk 4]
```diff
@@ -38,7 +38,7 @@ function plotQualificationComparisonTimeProfile(WSettings,figureHandle,CompTimeP
     [csvSimFile, xmlfile] = getSimFile(Curves{i}, SimulationMappings, REInputPath);
     if isempty(csvSimFile)
         ME = MException('plotQualificationComparisonTimeProfile:notFoundInPath', ...
-            'In Comparison Time Profile plot %d, Mapping %d, Project "%s" or Simulation "%s" were not found in SimulationMappings', figureHandle, i, Curves{i}.Project, Curves{i}.Simulation);
+            'In Mapping %d, Project "%s" or Simulation "%s" were not found in SimulationMappings', i, Curves{i}.Project, Curves{i}.Simulation);
```
Comment (Yuri05) [inline src/code/qualification/plotQualificationComparisonTimeProfile.m]: @pchelle ~Why did u remove "Comparison time profile N" from the error message? It is really helpfull wenn looking for errors!Same questions for all other plot kinds below.~

Ok, I see: that's because `figureHandle `is not passed anymore to the functions.

I would suggest to:
1. Remove all usages of figureHandle in all **plotQualificationXXX** functions.
e.g. replace [`ax = getReportFigureQP(WSettings,1,1,figureHandle,PlotSettings);`](https://github.com/pchelle/Reporting-Engine/blob/ecd7206999930a0197ba96158ee7f5fe6c33fa5d/src/code/qualification/plotQualificationComparisonTimeProfile.m#L28) 
with `ax = getReportFigureQP(WSettings,1,1,[],PlotSettings);`
2. Rename `figureHandle` parameter in all **plotQualificationXXX** functions to something like `plotIndex`
3. In **runQualificationWorkflow**: pass `plotIndex` to every **plotQualificationXXX** function
4. Finally in all error messages: restore removed parts of the error message (using the `plotIndex `now)

Comment (pchelle) [reply src/code/qualification/plotQualificationComparisonTimeProfile.m]: Yes, I will add these update asap.
There was another reason why I removed it: I noticed that the plot number is actually already displayed by the the try/catch of runQualificationWorkflow, consequently the plot Index information is redundant.

File: src/code/qualification/runQualificationWorkflow.m [hunk 5]
```diff
@@ -129,21 +129,21 @@ function runQualificationWorkflow(WSettings, ConfigurationPlan, TaskList, Observ
...
-                GOFMerged=ConfigurationPlan.Plots.GOFMergedPlots{j};
+            if iscell(ConfigurationPlan.Plots.GOFMergedPlots(GOFMergedIndex))
+                GOFMerged=ConfigurationPlan.Plots.GOFMergedPlots{GOFMergedIndex};
             else
-                GOFMerged=ConfigurationPlan.Plots.GOFMergedPlots(j);
+                GOFMerged=ConfigurationPlan.Plots.GOFMergedPlots(GOFMergedIndex);
             end
             
-            for k=1:length(GOFMerged)
+            for GOFMergedGroupIndex=1:length(GOFMerged)
```
Comment (Yuri05) [inline src/code/qualification/runQualificationWorkflow.m]: This for loop `for GOFMergedGroupIndex=1:length(GOFMerged.Groups) ` seems to be useless??
`length(GOFMerged)` is always 1 and here (in **runQualificationWorkflow**) there is no need to loop through the Groups anyway? (loop through the Groups is done in **plotQualificationGOFMerged**)
Or do I miss something?

Comment (pchelle) [reply src/code/qualification/runQualificationWorkflow.m]: You are completely right,
I just removed the loop.

File: src/code/qualification/plotQualificationDDIRatio.m (hunk 2 above)
Comment (Yuri05) [reply src/code/qualification/plotQualificationDDIRatio.m:206]: After discussing with @sfrechen : this is not correct.
I will merge the PR now to move forward and create a separate issue for this
