### PR TITLE
Fixes #124 Running test cases generates ill formatted graphics or even throws errors

### LINKED ISSUE #124: Running test cases generates ill formatted graphics or even throws errors
I ran the 3 test cases, Aciclovir, Rifampicin, and Theophylline. As recommended, I manually copied the file "content.md" from each test projects "input" directory to "input_re". The Matlab version used was 2018b.

**1. Case Aciclovir:** 
Executing "QualificationWorkflow.m" ran through. However, the plots seem to be extending outside the plot area. I attach the produced plots as an example.
[Tralala.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3171623/Tralala.zip)

**2. Case Rifampicin:** 
The following messages appeared:
Warning: Directory already exists. 
> In QualificationWorkflow (line 14) 
INFO: report-configuration-plan.json was extracted successfully
Warning: Directory already exists. 
> In generateOutputFolders (line 36)
  In QualificationWorkflow (line 22) 
Undefined function or variable 'ObservedDataSets'.

Error in QualificationWorkflow (line 79)
runQualificationWorkflow(WSettings, ConfigurationPlan, TaskList, ObservedDataSets);

**3. Case  Theophylline:**
Not plots were generated, the following messages appeared:
Warning: Directory already exists. 
> In QualificationWorkflow (line 14) 
INFO: report-configuration-plan.json was extracted successfully
Warning: Directory already exists. 
> In generateOutputFolders (line 36)
  In QualificationWorkflow (line 22) 
INFO: Start Workflow:  Project specified workflowTye Qualification mode default 
 System is NOT validated 
 Computer _MyPcName_ (PCWIN64) 
 Reporting Engine version: 2 
 Open Systems Pharmacology Suite version: 7.2 
 Version of SimModel: 2.2 
 SimModelCompName: OSPSuite_SimModelComp.xml 
 Matlab version: 9.5.0.944444 (R2018b) 
 Started by: _myUserId_ 

Initialisation of Theophylline\Henrist oral Hot stage extrusion as table\Henrist oral Hot stage extrusion as table.xml
Number of VariableParameters: 0, with formulas: 0, table parameters: 0
Number of VariableSpecies: 0, with formulas: 0 
ERROR: Error in TimeProfile plot 1. 
 Curves 3 : Data|ObservedData|Undefined|Undefined|Theophylline|% dissolved not found 

Warning: Error in TimeProfile plot 1.
 Curves 3 : Data|ObservedData|Undefined|Undefined|Theophylline|% dissolved not found
 
> In runQualificationWorkflow (line 125)
  In QualificationWorkflow (line 79) 
Initialisation of Theophylline\Kaumeier IV 208 mg fit\Kaumeier IV 208 mg fit.xml
Number of VariableParameters: 0, with formulas: 0, table parameters: 0
Number of VariableSpecies: 0, with formulas: 0 
ERROR: Error in TimeProfile plot 2. 
 Index exceeds array bounds. 

Warning: Error in TimeProfile plot 2.
 Index exceeds array bounds.
 
> In runQualificationWorkflow (line 125)
  In QualificationWorkflow (line 79) 
Initialisation of Theophylline\Kaumeier oral solution 185mg\Kaumeier oral solution 185mg.xml
Number of VariableParameters: 0, with formulas: 0, table parameters: 0
Number of VariableSpecies: 0, with formulas: 0 
ERROR: Error in TimeProfile plot 3. 
 Index exceeds array bounds. 

Warning: Error in TimeProfile plot 3.
 Index exceeds array bounds.
 
> In runQualificationWorkflow (line 125)
  In QualificationWorkflow (line 79)

### LINKED ISSUE #172: Watermarks in non-validated environments
When running a RE-workflow in a non-validated environment for the first time: user must be asked if watermarks should be used in the plots.
This will be saved as a user setting.

### PR DESCRIPTION
**Pull request by Yuri05**
Fixes #172 Watermarks in non-validated environments

### CODE REVIEW

File: src/code/engine_library/initializeWorkflow.m [hunk 1]
```diff
@@ -25,6 +25,35 @@
...
+           while isempty(answer)
+              answer=inputdlg(prompt,name,numlines,defaultanswer);
+           end
+           watermark = answer{1};
+           save(fullfile(userDir,'watermark.mat'),'watermark');
+        end
+        WSettings.Watermark = watermark;
+    end
+end
+
```
Comment (Yuri05) [inline src/code/engine_library/initializeWorkflow.m:55]: This shows the dialog below
grafik
Setting value to empty disables watermarks.

**Comment by Yuri05** [comment]
Merging to move forward.
@KatrinCoboeken You can still review
