### PR TITLE
Fixes #203 wrong GMFE Calculation

### LINKED ISSUE #203: wrongly inserted GMFE function in plotQualificationPKRatio.m
In matlab, GMFE for the ratio plots is wrongly inserted into the plotQualificationPKRatio.m script.

Please correct:

% Calculation of GMFE
GMFE = 10.^(sum(abs(log(Result.RatioPK)))./length(Result.obsPK));
for k=1:length(PKParameter)
    fprintf('%s: GMFE = %f \n', PKParameter{k}, GMFE(k));
end

Into

% Calculation of GMFE
GMFE = 10.^(sum(abs(log10(Result.RatioPK)))./length(Result.obsPK));
for k=1:length(PKParameter)
    fprintf('%s: GMFE = %f \n', PKParameter{k}, GMFE(k));
end

in plotQualificationGOFMerged.m it is correct.

### PR DESCRIPTION
**Pull request by msevestre**
Also the file was not saved in UTF-8. Hence the changes everywhere

### CODE REVIEW

File: src/code/qualification/plotQualificationPKRatio.m [hunk 1]
```diff
@@ -226,7 +226,7 @@
 disp(PKRatioTable);
 
 % Calculation of GMFE
-GMFE = 10.^(sum(abs(log(Result.RatioPK)))./length(Result.obsPK));
+GMFE = 10.^(sum(abs(log10(Result.RatioPK)))./length(Result.obsPK));
```
Comment (msevestre) [inline src/code/qualification/plotQualificationPKRatio.m:229]: This is the real change here.
