### PR TITLE
140 cell inputs

### LINKED ISSUE #125: Default plots are too small

### LINKED ISSUE #132: Use full path for xml files

### LINKED ISSUE #139: "Too many outputs requested"
Input: https://github.com/Yuri05/QualiExample01

Might be a follow-up error of #132(?)

```
Initialisation of Midazolam-Model\po 3 mg (solution)\po 3 mg (solution).xml
Number of VariableParameters: 0, with formulas: 0, table parameters: 0
Number of VariableSpecies: 0, with formulas: 0 
ERROR: Error in TimeProfile plot 25. 
 Too many outputs requested.  Most likely cause is missing [] around left hand side that has a comma separated list expansion. 
```

### LINKED ISSUE #140: "Function is not defined for 'cell' inputs"
Input: https://github.com/Yuri05/QualiExample01

Might be a follow-up error of #132(?)

```
Initialisation of Rifampicin-Model\Rifampicin iv 300 mg (3 h)\Rifampicin iv 300 mg (3 h).xml
Number of VariableParameters: 0, with formulas: 0, table parameters: 0
Number of VariableSpecies: 0, with formulas: 0 
ERROR: Error in TimeProfile plot 56. 
 Function is not defined for 'cell' inputs.
```

### LINKED ISSUE #142: "Scalar structure required for this assignment"
Input: https://github.com/Yuri05/QualiExample01

```
In runQualificationWorkflow (line 240)
  In QualificationWorkflow (line 23) 
Scalar structure required for this assignment.

Error in runQualificationWorkflow (line 329)
                    AxesOptions.DDIRatioPlotsPredictedVsObserved=AxesSettings(l).DDIRatioPlotsPredictedVsObserved;
                    
Error in QualificationWorkflow (line 23)
runQualificationWorkflow(WSettings, ConfigurationPlan, TaskList, ObservedDataSets);
```

### PR DESCRIPTION
**Pull request by pchelle**
Fixes #125 Fixes #132 Fixes #139 Fixes #140 Fixes #142

### CODE REVIEW

File: src/code/qualification/getMolecularWeightForPath.m [hunk 1]
```diff
@@ -20,6 +20,11 @@
 
 jj = cellfun(@(x) contains([outputPath '|'],x),strcat('|',compounds,'|'));
 
+if sum(jj)~=1
+    disp(jj);
+    jj=1; 
+end
+
```
Comment (Yuri05) [inline src/code/qualification/getMolecularWeightForPath.m:27]: can you explain what happens here in the lines 23-26?

File: src/code/qualification/getSimFile.m [hunk 2]
```diff
@@ -25,7 +25,7 @@
             strcmp(SimulationMapping(i).Simulation, Simulation)
         
         path = SimulationMapping(i).Path;
-        csvSimFile = fullfile(path, [Simulation '-Results.csv']);
-        xmlSimFile = fullfile(path, [Simulation '.xml']);
+        csvSimFile = fullfile(pwd, path, [Simulation '-Results.csv']);
+        xmlSimFile = fullfile(pwd, path, [Simulation '.xml']);
```
Comment (Yuri05) [inline src/code/qualification/getSimFile.m:29]: `pwd `is the current folder. When the code is executed: is this always the folder of the _RE_configuration_plan_?

File: src/code/qualification/getMolecularWeightForPath.m (hunk 1 above)
Comment (pchelle) [reply src/code/qualification/getMolecularWeightForPath.m:27]: These lines were for me to debug the issue with getMolecularWeightForPath: for some Paths the cellfun seems unable to find the compound and provides an empty output leading to issue #139. 
I have forgotten to replace the lines with a warning or error message.

File: src/code/qualification/getSimFile.m (hunk 2 above)
Comment (pchelle) [reply src/code/qualification/getSimFile.m:29]: So far it is. But it may be better if I allow the Qualification Workflow to be run from any directory.
I will add an issue for this and make the updates.
